using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Concord.Generators;

/// <summary>
///     Emits the assembly patch registry: an <c>internal</c> type listing every <c>[Patch]</c>
///     declaration, pointed at by an assembly-level <c>[PatchRegistry]</c> attribute, so
///     <c>Patcher.Apply</c> enumerates declarations without a reflection scan.
/// </summary>
[Generator]
public sealed class PatchRegistryGenerator : IIncrementalGenerator {
    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context) {
        IncrementalValuesProvider<string?> declarations = context.SyntaxProvider.ForAttributeWithMetadataName(
            "Concord.PatchAttribute",
            static (node, _) => node is ClassDeclarationSyntax,
            static (ctx, _) => {
                if (ctx.TargetSymbol is not INamedTypeSymbol symbol || symbol.IsGenericType) {
                    return null;
                }

                return symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            });

        context.RegisterSourceOutput(declarations.Collect(), static (productionContext, names) => {
            List<string> sorted = [];
            foreach (string? name in names) {
                if (name is not null) {
                    sorted.Add(name);
                }
            }

            if (sorted.Count == 0) {
                return;
            }

            sorted.Sort(StringComparer.Ordinal);

            StringBuilder source = new StringBuilder();
            source.AppendLine("// <auto-generated/>");
            source.AppendLine("[assembly: global::Concord.PatchRegistry(typeof(global::Concord.Generated.PatchRegistry))]");
            source.AppendLine();
            source.AppendLine("namespace Concord.Generated {");
            source.AppendLine("    internal sealed class PatchRegistry : global::Concord.IPatchDeclarationProvider {");
            source.AppendLine("        public global::System.Collections.Generic.IReadOnlyList<global::System.Type> Declarations { get; } = new global::System.Type[] {");
            foreach (string name in sorted) {
                source.AppendLine("            typeof(" + name + "),");
            }

            source.AppendLine("        };");
            source.AppendLine("    }");
            source.AppendLine("}");

            productionContext.AddSource("ConcordPatchRegistry.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
        });
    }
}
